In [1]:
print("sup it's sigmaward")

sup it's sigmaward

### Loading the data

In [7]:
#just testing with pandas 

import pandas as pd

file = "customer_churn.csv"

df = pd.read_csv(file)

df

,CustomerID,Age,Subscription_Length_Months,Watch_Time_Hours,Number_of_Logins,Preferred_Content_Type,Membership_Type,Payment_Method,Payment_Issues,Number_of_Complaints,Resolution_Time_Days,Churn
0,1,56,35,62.579266,73,TV Shows,Basic,PayPal,0,7,8,0
1,2,69,15,159.714415,1,Sports,Basic,Credit Card,0,7,21,0
2,3,46,25,41.119547,36,Movies,Premium,PayPal,0,5,13,1
3,4,32,28,183.961735,35,Movies,Standard,Credit Card,0,0,27,0
4,5,60,10,87.782848,66,Movies,Standard,Bank Transfer,0,7,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,60,31,128.416734,68,Movies,Premium,Credit Card,0,9,4,1
996,997,64,10,18.460760,12,Movies,Premium,Credit Card,0,2,11,1
997,998,62,13,6.104834,60,Documentaries,Premium,Credit Card,0,0,5,0
998,999,35,31,187.732751,27,TV Shows,Basic,Bank Transfer,1,8,2,0
999,1000,55,7,165.275694,56,Movies,Basic,Bank Transfer,0,9,17,0

In [10]:
df.shape

(1000, 12)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CustomerID                  1000 non-null   int64
 1   Age                         1000 non-null   int64
 2   Subscription_Length_Months  1000 non-null   int64
 3   Watch_Time_Hours            1000 non-null   float64
 4   Number_of_Logins            1000 non-null   int64
 5   Preferred_Content_Type      1000 non-null   object
 6   Membership_Type             1000 non-null   object
 7   Payment_Method              1000 non-null   object
 8   Payment_Issues              1000 non-null   int64
 9   Number_of_Complaints        1000 non-null   int64
 10  Resolution_Time_Days        1000 non-null   int64
 11  Churn                       1000 non-null   int64
dtypes: float64(1), int64(8), object(3)
memory usage: 93.9+ KB